/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp screenlockbusinesslogic.xml -a screenlockbusinesslogicadaptor -c ScreenLockBusinessLogicAdaptor -l ScreenLockBusinessLogic -i screenlockbusinesslogic.h -i metatypedeclarations.h
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef SCREENLOCKBUSINESSLOGICADAPTOR_H_1368685876
#define SCREENLOCKBUSINESSLOGICADAPTOR_H_1368685876

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "screenlockbusinesslogic.h"
#include "metatypedeclarations.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.system_ui.request
 */
class ScreenLockBusinessLogicAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.system_ui.request")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.system_ui.request\">\n"
"    <method name=\"tklock_open\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"service\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"path\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"interface\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"method\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"mode\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"silent\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"flicker\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"tklock_close\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"silent\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"status\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ScreenLockBusinessLogicAdaptor(ScreenLockBusinessLogic *parent);
    virtual ~ScreenLockBusinessLogicAdaptor();

    inline ScreenLockBusinessLogic *parent() const
    { return static_cast<ScreenLockBusinessLogic *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int tklock_close(bool silent);
    int tklock_open(const QString &service, const QString &path, const QString &interface, const QString &method, uint mode, bool silent, bool flicker);
Q_SIGNALS: // SIGNALS
};

#endif
